### ISSUE TITLE
Elixir 1.17.3 OTP 27 mix tz_world.update fails with :http_util is not available

### ISSUE THREAD

**Issue by muej** [kimlai/tz_world#46]
Hi,

first of all, thank you for this library. Unfortunately I do get the following error, when running `mix tz_world.update`.

``` elixir
** (UndefinedFunctionError) function :http_util.timestamp/0 is undefined (module :http_util is not available)
    (inets 9.3) :http_util.timestamp()
    (inets 9.3) httpc.erl:1151: :httpc.handle_request/9
    (tz_world 1.4.1) lib/tz_world/downloader.ex:409: TzWorld.Downloader.get_with_headers/2
    (tz_world 1.4.1) lib/tz_world/downloader.ex:253: TzWorld.Downloader.get/2
    (tz_world 1.4.1) lib/tz_world/downloader.ex:120: TzWorld.Downloader.get_releases/1
    (tz_world 1.4.1) lib/tz_world/downloader.ex:27: TzWorld.Downloader.latest_release/2
    (tz_world 1.4.1) lib/mix/tasks/update_timezones_geojson.ex:79: Mix.Tasks.TzWorld.Update.update/3
    (mix 1.17.3) lib/mix/task.ex:495: anonymous fn/3 in Mix.Task.run_task/5
```
It is run in a `elixir:1.17.3-otp-27-alpine` docker image.

``` shell
$ docker run --rm -ti elixir:1.17.3-otp-27-alpine elixir -v
Erlang/OTP 27 [erts-15.1.2] [source] [64-bit] [smp:6:6] [ds:6:6:10] [async-threads:1] [jit]

Elixir 1.17.3 (compiled with Erlang/OTP 27)
```

I was not able to track it down. :(

**Comment by muej** [comment]
Adding

``` elixir
﻿      prune_code_paths: Mix.env() == :prod,
```
to mix project helped.

**Comment by muej** [comment]
Any other way to keep it from pruning? I thought loading `:inets` would already do, but obviously not.

**Comment by kipcole9** [comment]
Thats very strange.`http_util` is part of the `inets` application so the module should be found. I can't reproduce either on my development Mac using Elixir 1.17.3-otp-27 and top 27.1.

```bash
% asdf current
elixir          1.17.3-otp-27   /Users/kip/Development/tz_world/.tool-versions
erlang          27.1            /Users/kip/.tool-versions

% mix tz_world.update
05:16:55.089 [info] [TzWorld] Updating from release 2024a to 2024b.
```

All the issues created in other libs also noted that adding `inets` to `:extra_applications` resolves the issue - and `inets` has been defined for `tz_world` for quite a few releases.

Can you confirm what version of `tz_world` you are running?

**Comment by muej** [comment]
It is
```elixir
  "tz_world": {:hex, :tz_world, "1.4.1", "ff9c9819b20f443d47e6e0dc412e15c23be5bb6ac856e8d83c4163ccbc55b52f", ...},
```
I played a little bit around and also can not reproduce it on my dev environment (Mac M2). What is very strange, when I run it in the alpine container, I do get a different scenario, ie. just a `killed` line and iex is gone without any other information.

```
❯ docker run --rm -ti elixir:1.17.3-otp-27-alpine /bin/sh
/ # iex
Erlang/OTP 27 [erts-15.1.2] [source] [64-bit] [smp:6:6] [ds:6:6:10] [async-threads:1] [jit]

Interactive Elixir (1.17.3) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> Mix.install([{:tz_world, "~> 1.4"}])
* creating /root/.mix/archives/hex-2.1.1
Resolving Hex dependencies...
Resolution completed in 0.239s
New:
  geo 4.0.1
  jason 1.4.4
  tz_world 1.4.1
* Getting tz_world (Hex package)
* Getting geo (Hex package)
* Getting jason (Hex package)
==> jason
Compiling 10 files (.ex)
Generated jason app
==> geo
Compiling 27 files (.ex)
Generated geo app
==> tz_world
Compiling 11 files (.ex)
Generated tz_world app
:ok
iex(2)> Mix.Tasks.TzWorld.Update.run(["--trace"])

09:12:55.036 [debug] [66 MiB] Retrieved list of 21 available timezone data releases.

09:12:55.036 [info] [TzWorld] No timezone geo data installed. Installing the latest release 2024b.

09:13:07.544 [debug] [1726 MiB] Transforming source data
Killed
/ #
```
So totally different story. :-/ That makes it hard to get grip on the situation.

**Comment by andrepaes** [comment]
> It is
> 
>   "tz_world": {:hex, :tz_world, "1.4.1", "ff9c9819b20f443d47e6e0dc412e15c23be5bb6ac856e8d83c4163ccbc55b52f", ...},
> 
> I played a little bit around and also can not reproduce it on my dev environment (Mac M2). What is very strange, when I run it in the alpine container, I do get a different scenario, ie. just a `killed` line and iex is gone without any other information.
> 
> ```
> ❯ docker run --rm -ti elixir:1.17.3-otp-27-alpine /bin/sh
> / # iex
> Erlang/OTP 27 [erts-15.1.2] [source] [64-bit] [smp:6:6] [ds:6:6:10] [async-threads:1] [jit]
> 
> Interactive Elixir (1.17.3) - press Ctrl+C to exit (type h() ENTER for help)
> iex(1)> Mix.install([{:tz_world, "~> 1.4"}])
> * creating /root/.mix/archives/hex-2.1.1
> Resolving Hex dependencies...
> Resolution completed in 0.239s
> New:
>   geo 4.0.1
>   jason 1.4.4
>   tz_world 1.4.1
> * Getting tz_world (Hex package)
> * Getting geo (Hex package)
> * Getting jason (Hex package)
> ==> jason
> Compiling 10 files (.ex)
> Generated jason app
> ==> geo
> Compiling 27 files (.ex)
> Generated geo app
> ==> tz_world
> Compiling 11 files (.ex)
> Generated tz_world app
> :ok
> iex(2)> Mix.Tasks.TzWorld.Update.run(["--trace"])
> 
> 09:12:55.036 [debug] [66 MiB] Retrieved list of 21 available timezone data releases.
> 
> 09:12:55.036 [info] [TzWorld] No timezone geo data installed. Installing the latest release 2024b.
> 
> 09:13:07.544 [debug] [1726 MiB] Transforming source data
> Killed
> / #
> ```
> 
> So totally different story. :-/ That makes it hard to get a grip on the situation.

hey, any update on this?

**Comment by kipcole9** [comment]
No update I'm afraid - I haven't been able to reproduce.  I can only surmise (unscientifically) that there is an OOM issue when transforming the data. Basically at the point of you seeing "Killed" [the code is](https://github.com/kimlai/tz_world/blob/master/lib/tz_world/geo_data.ex#L33-L40):
```elixir
  def generate_compressed_data(source_data, version, trace? \\ false) when is_list(source_data) do
    maybe_log("Transforming source data", trace?)
    binary_data = transform_source_data(source_data, version)
    maybe_log("Transformed source data", trace?)
    :erlang.garbage_collect()
    :zip.zip(compressed_data_path(), [{etf_data_path(), binary_data}])
    maybe_log("Compressed data into a zip file", trace?)
  end

  def transform_source_data(source_data, version) when is_binary(source_data) do
    case :zip.unzip(source_data, [:memory]) do
      {:ok, [{_, json} | _rest]} ->
        json
        |> decode_json(version)
        |> :erlang.term_to_binary()

      error ->
        raise RuntimeError, "Unable to unzip downloaded data. Error: #{inspect(error)}"
    end
  end

  defp decode_json(json, version) do
    json
    |> json_decode!()
    |> Geo.JSON.decode!()
    |> Map.fetch!(:geometries)
    |> Enum.map(&update_map_keys/1)
    |> Enum.map(&calculate_bounding_box/1)
    |> List.insert_at(0, version)
  end
```

The reason I'm thinking its an OOM issue is that `:zip.unzip(source_data, [:memory])` combined with manipulating the JSON is likely a big consumer of memory.

Would you be able to give your Docker container more memory and see if that has an affect?

**Comment by kipcole9** [comment]
I've been trying to test this in docker but even after 24 hours I'm getting the dreaded 403 Rate Limit Exceeded from GitHub.

**Comment by kipcole9** [comment]
@andrepaes 

> after that and inserting :inets on extra_applications it solved

`:inets` is part of `:extra_applications` in the published package. Did you still have to do something in addition?
